name: Build Waterfall
on:
  push:
    branches:
      - master
      - actions #temp
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Install Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: patch
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./travertine p
      - name: build
        run: mvn clean javadoc:javadoc package

      - name: Upload Artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: Artifact
          path: Travertine-Proxy/*

